### ISSUE TITLE
Works on localhost but not deployed

### ISSUE THREAD

**Issue by lonelydatum** [hoangvvo/next-session#129]
Thank you so much for this amazing project.

Is there a special configuration to ensure it works on the server? It's deployed on the *.now.sh.
This is my current configuration
cookie: {        
        path: "/",        
        maxAge: 60*60*24*14*1000
}

Thanks.

**Comment by hoangvvo** [comment]
Are you using the default `MemoryStore`? It does not work in serverless environment. Try using stores like `redis-connect` or `mongo-connect` should do.

**Comment by lonelydatum** [comment]
Oh, I didn't know it doesn't work in a serverless environment. Thanks for the suggestion, I'll check it out.

**Comment by hoangvvo** [comment]
Thank you for pointing it out though. I will update the docs with this info. Let me know if it works

**Comment by NicholasG04** [comment]
Any advice on how to do this in a serverless environment? Are there stores that do work in a serverless environment, since I assume redis/mongo require a server?

**Comment by NicholasG04** [comment]
Can confirm, have just tried deploying to vercel by using ioredis. Works perfectly :)

**Comment by hoangvvo** [comment]
@lonelydatum Close since it should be solved using an external session store. Also make sure that `maxAge` is in second (you do not want that `*1000`)
