### ISSUE TITLE
connectMongo type check from example documentation

### ISSUE THREAD

**Issue by albertpeiro** [hoangvvo/next-session#140]
Hi I'm doing this:
```
import Session, {
  session,
  promisifyStore,
  Store,
  MemoryStore,
} from "next-session";
import connectMongo from "connect-mongo";

const MongoStore = connectMongo({ Store, MemoryStore });

declare module "next" {
  interface NextApiRequest {
    session: any;
  }
}

export default function (req, res, next) {
  const mongoStore = new MongoStore({
    mongooseConnection: req.mongooseConnection, // see how we use req.dbClient from the previous step
    stringify: true,
    secret: "squirrel",
  });
  return session({
    store: promisifyStore(mongoStore),
  })(req, res, next);
}

```

and I'm getting this type error:
<img width="1184" alt="Screenshot 2020-05-19 at 22 11 04" src="https://user-images.githubusercontent.com/1984397/82379047-234a7500-9a1e-11ea-8f7a-959be3be90ea.png">

I'm using:
```
    "connect-mongo": "^3.2.0",
    "mongoose": "^5.9.14",
    "next": "9.4.1",
    "next-connect": "^0.6.6",
    "next-session": "^3.1.0",
```
However the basic session functionality seems to work - but haven't tested extensively.
What can I do to fix this?

**Comment by EtienneK** [comment]
Yeah, experiencing the same issue. Also, would be nice if this project supported TypeScript types as well.

**Comment by hoangvvo** [comment]
Thanks for the issue. I am aware of this and intending to rewrite `next-session` with TypeScript really soon.

**Comment by hoangvvo** [comment]
It's kinda ugly to rewrite this library in TypeScript since it mutates `IncomingMessage`.

I am nowhere good in TypeScript so it would be great if anyone can chime in on #147.

**Comment by hoangvvo** [comment]
I take a look in source code of `connect-mongo` and see that the factory function does expect `connect.Store` (connect is the argument `connectMongo` factory function)

https://github.com/jdesboeufs/connect-mongo/blob/master/src/index.js#L57

The way its type was written is kinda *not compatible* type-wise. After all, `connect-mongo` is written for `express-session`.

**Comment by hoangvvo** [comment]
Try out the TypeScript rewrite in `v3.2.1` and let me know if it works.

`connectMongo` should be safe to `@ts-ignore`

**Comment by hoangvvo** [comment]
@EtienneK @albertpeiro  Use `v3.2.3` and the new `expressSession` named export should resolve the TS error! Feel free to reopen if this still occurs. See [this](https://github.com/hoangvvo/next-session#compatibility-with-expressconnect-stores)

**Comment by albertpeiro** [comment]
@hoangvvo it does!
Thank you very much for looking into this and fixing it so quickly.
Feel free to contact me if you need any help or collaboration.
