### ISSUE TITLE
Breaking: Use Map for Session data

### ISSUE THREAD

**Issue by hoangvvo** [hoangvvo/next-session#154]
In the next major version (v4), `next-session` will use [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) for session.

For example, the new methods for session values would be `.get`, `.set`, etc.

**Comment by pedox** [comment]
I have some issue with my current project (i am using typescript) with current v3 packages. Everything is ok but when i update to last version `3.2.2` some scripts are broken.

like some type changes on custom store definition that previously called `Store` it changes to `StoreInterface` , that breaks my my current code, but it's ok, so the solution is i revert back to version `3.1.0`

*sorry for my bad english*

**Comment by pedox** [comment]
Here is my custom Store if you curious

```ts
import mongoose, { Document, model, Model, Schema } from 'mongoose'
import { Store } from 'next-session'
import { v4 as uuidv4 } from 'uuid'

mongoose.models = mongoose.models || {}

export const SessionSchema = new Schema(
  {
    _id: {
      type: String,
      default: uuidv4,
    },
    data: {
      type: Object,
    },
  },
  { timestamps: {} }
)

export interface Session {
  _id?: string
  data: Object
}

export interface SessionDocument extends Session, Document {
  _id: string
}

export const SessionModel: Model<SessionDocument> =
  (mongoose.models.Session as Model<SessionDocument>) ||
  model<SessionDocument>('Session', SessionSchema)

export class MongooseStore extends Store {
  constructor() {
    super()
  }

  get = async sid => {
    const doc = await SessionModel.findById(sid)
    if (doc) return doc.data
    return null
  }

  set = async (sid, data) => {
    const doc = await SessionModel.findById(sid)
    if (doc) {
      doc.data = data
      return await doc.save()
    }
    return await SessionModel.create({ _id: sid, data })
  }

  touch = async (sid, data) => {
    const doc = await SessionModel.findById(sid)
    if (doc) {
      doc.data = data
      return await doc.save()
    }
    return await SessionModel.create({ _id: sid, data })
  }

  destroy = async sid => {
    return await SessionModel.findByIdAndRemove(sid)
  }
}
```

**Comment by hoangvvo** [comment]
> Here is my custom Store if you curious
> 
> 
> 
> ```ts
> 
> import mongoose, { Document, model, Model, Schema } from 'mongoose'
> 
> import { Store } from 'next-session'
> 
> import { v4 as uuidv4 } from 'uuid'
> 
> 
> 
> mongoose.models = mongoose.models || {}
> 
> 
> 
> export const SessionSchema = new Schema(
> 
>   {
> 
>     _id: {
> 
>       type: String,
> 
>       default: uuidv4,
> 
>     },
> 
>     data: {
> 
>       type: Object,
> 
>     },
> 
>   },
> 
>   { timestamps: {} }
> 
> )
> 
> 
> 
> export interface Session {
> 
>   _id?: string
> 
>   data: Object
> 
> }
> 
> 
> 
> export interface SessionDocument extends Session, Document {
> 
>   _id: string
> 
> }
> 
> 
> 
> export const SessionModel: Model<SessionDocument> =
> 
>   (mongoose.models.Session as Model<SessionDocument>) ||
> 
>   model<SessionDocument>('Session', SessionSchema)
> 
> 
> 
> export class MongooseStore extends Store {
> 
>   constructor() {
> 
>     super()
> 
>   }
> 
> 
> 
>   get = async sid => {
> 
>     const doc = await SessionModel.findById(sid)
> 
>     if (doc) return doc.data
> 
>     return null
> 
>   }
> 
> 
> 
>   set = async (sid, data) => {
> 
>     const doc = await SessionModel.findById(sid)
> 
>     if (doc) {
> 
>       doc.data = data
> 
>       return await doc.save()
> 
>     }
> 
>     return await SessionModel.create({ _id: sid, data })
> 
>   }
> 
> 
> 
>   touch = async (sid, data) => {
> 
>     const doc = await SessionModel.findById(sid)
> 
>     if (doc) {
> 
>       doc.data = data
> 
>       return await doc.save()
> 
>     }
> 
>     return await SessionModel.create({ _id: sid, data })
> 
>   }
> 
> 
> 
>   destroy = async sid => {
> 
>     return await SessionModel.findByIdAndRemove(sid)
> 
>   }
> 
> }
> 
> ```
> 
> 
> 
> 
> 
> ```ts
> 
> return session({
> 
>   store: new MongooseStore(),
> 
> })(req, res, next)
> 
> ```

Sorry for the confusion. You should not extend from Store. Store is a compatible layer for express-session callback stores.

**Comment by hoangvvo** [comment]
But that may not be the cause though. What error are you seeing?

**Comment by hoangvvo** [comment]
Hey @pedox, `{ Store }` is the compatible layer for `express-session` stores, and you should not use it. You don't have to extend anything for the custom store.

**Comment by pedox** [comment]
here my errors
```js
23:5 Type 'MongooseStore' is not assignable to type 'IStore'.
  The types returned by 'get(...)' are incompatible between these types.
    Type 'Promise<Object>' is not assignable to type 'Promise<SessionData>'.
      The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
        Property 'cookie' is missing in type 'Object' but required in type 'SessionData'.
    21 |   await ConnectDB()
    22 |   return session({
  > 23 |     store: new MongooseStore(),
       |     ^
    24 |   })(req, res, next)
    25 | }
    26 | 
```

but after your explain that, maybe that was my mistake, im just seeing example code of your previous MemoryStore provider, i thought it was same.

https://github.com/hoangvvo/next-session/blob/0714ccc53d1b53d3f7fb8317b848661304f15afe/src/store/memory.js#L1-L66

**Comment by pedox** [comment]
but anyways thanks for bring Typescript for next major release :+1:

**Comment by hoangvvo** [comment]
@pedox Ah, I see. It's actually fine to extend Store. Store is merely an `EventEmitter` (which is used by most express-session stores), which can be helpful in informing the readiness of your store (using `.emit`)

The problem is in your interface `Session`, which has the property `data` of `Object`. That will not be compatible. It must be `SessionData`, which I think you can import from `next-session`.

**Comment by pedox** [comment]
@hoangvvo ohh i get it!, will try that, thank you
