### ISSUE TITLE
res.redirect() doesn't set actual session cookie

### ISSUE THREAD

**Issue by plashenkov** [hoangvvo/next-session#236]
Hi!

I'm using the following code to authenticate a user using passport.js:

```ts
import nextConnect from 'next-connect'
import {middleware} from 'src/core/middleware'
import {passport} from 'src/core/passport'

export default nextConnect()
  .use(middleware)
  .get(passport.authenticate('github', {successRedirect: '/'}))
```

> Not so important, but FYI: `middleware` includes database and next-session configuration, passport.initialize(), passport.session(). As far as I can see everything configured properly.

It works well if I do not use a redirect after successful authentication.
For example, this code works well:

```ts
export default nextConnect()
  .use(middleware)
  .get(passport.authenticate('github'))
  .get(function (req, res) {
    res.json({user: req.user});
  })
```

The result of this code: session is set correctly, the browser cookie points to the correct session.

But if I replace `res.json()` with redirect: `res.redirect('/')`, or use `{successRedirect: '/'}` parameter of passport.js, then the valid session cookie simply not set. I can see the correct session in my Redis storage, but the browser still holds the previous cookie, and the correct one is simply lost.

What's wrong with redirects? Why they lose the correct cookie and how to workaround this?

Thanks!

**Comment by hoangvvo** [comment]
Hey @plashenkov, what are your cookie options?

**Comment by plashenkov** [comment]
Here they are:

```ts
const middleware = session({
  store: promisifyStore(new RedisStore({client: redis})),
  rolling: true,
  cookie: {
    secure: true,
    httpOnly: true,
    sameSite: 'lax',
    maxAge: 7 * 24 * 60 * 60,
  }
})
```

**Comment by plashenkov** [comment]
Manually setting cookie works as well:

```ts
// ...
  .use(function (req, res) {
    res.setHeader('Set-Cookie', req.session.cookie.serialize(req._sessOpts.name, req.sessionId))
    res.redirect('/')
  })
```

But I believe it should work without hacky workarounds :)

**Comment by plashenkov** [comment]
`res.redirect()` means `res.writeHead(...).end()`
Maybe this blocks something from settings correct cookie header?

**Comment by hoangvvo** [comment]
Oooh, that might be the case. Calling writeHead sends the header so next-session does not get to set the cookie header.

**Comment by plashenkov** [comment]
Do you have any ideas on how this can be solved nicely?
When using authentication system and next-session together: redirect is often needed after successful login, especially with OAuth.
I thought next-session writes headers and modifies the response object in its own middleware, and my custom code which is at the end is really executed at the end.

**Comment by hoangvvo** [comment]
For now you can try what you suggested above, but instead just do await req.session.commit() instead of calling that res.setHeader. 

I would need to push a PR to address this but won't be able to until next week. The idea would be to apply the same thing to what we do with res.end (see in code) to res.writeHead.

**Comment by plashenkov** [comment]
> For now you can try what you suggested above, but instead just do await req.session.commit() instead of calling that res.setHeader.

Yup, it works for now!

> I would need to push a PR to address this but won't be able to until next week. The idea would be to apply the same thing to what we do with res.end (see in code) to res.writeHead.

Thanks, will look forward to it! :))
