### ISSUE TITLE
Add next-session usage for document middleware

### ISSUE THREAD

**Issue by dbachrach** [hoangvvo/next-session#24]
Hi, we are investigating session management with nextjs and like this project's approach. Attaching middleware for API routes works great. I'm not sure how this project works with fetching session data from the client-side code (i.e. how _app.js's `getInitialProps` can fetch session data). Since getInitialProps is executed and bundled for both client and server side code, how can Session Store (a postgres js library -- in our case) not be bundled into the client-side javascript? Even if it can be bundled, it's not going to be able to communicate to the postgres database since it's executing in the user's browser instead of our backend server.

Maybe the approach is to only do this in _document.js since that should be only bundled in a server bundle? This next RFC would be the ideal solution (I think) https://github.com/zeit/next.js/issues/7208

At the moment we are doing the following: Expose an API route /api/auth/session, which responds with JSON with session details. In the _app's `getInitialProps` we make an API call to this endpoint. That API call can be executed from client or server code.

Thanks!

**Comment by hoangvvo** [comment]
Hey @dbachrach, I do acknowledge this problem. Session management should only work server-side. Still, webpack will bundle it both client and server side. However, `next-session` will acknowledge if it is used in client-side and will not run. 

I'm looking at https://github.com/zeit/next.js/pull/5159. Basically, you should require the postgres library under the condition, and the library will not be bundled client-side.

```
if (!process.browser) {
   const thatPostGresLibrary = require('thatPostGresLibrary');
   // usage with `next-session` and your own logic here
}
```

It would be great if you can test it out for me.
Thanks.

**Comment by dbachrach** [comment]
When I went down this path I traced it through, and it appears that the removal in client bundles only occurs when running next in production builds. So it doesn't work with next in development mode-- it still tries to include the postgres lib into the client bundle.

I think we might have to wait for zeit/next.js#7208.

**Comment by dbachrach** [comment]
Actually this is already implemented for `_document.js` (https://github.com/zeit/next.js/pull/7209/files).

So in your nextjs.config.js you need:

```
module.exports = {
  experimental: {
    documentMiddleware: true
  }
};
```

In _document.js we add a middleware export:

```
const wrapSession = handler => withSession(handler, {});
const wrapDocument = handler => wrapSession(handler);

export const middleware = async ({ req, res }) => {
  // We need to remap the calling convention since nextjs's documentMiddleware takes ({req,res})
  // while normal api routes expect (req, res).
  await wrapDocument(() => {})(req, res);
};
```

Then in your _app.js getInitialProps you will have a req.session populated and do what you need.

Thoughts on making this the recommended implementation?

**Comment by hoangvvo** [comment]
@dbachrach Oh wow, thanks a lot for your througout investigation. I will certainly do so. I really wish Next.js documentation do include this.

Anyway, thanks again.
