### ISSUE TITLE
Does this work with a custom server like express?

### ISSUE THREAD

**Issue by WingmanImd** [hoangvvo/next-session#241]
Hello, I'm having issues trying to use next-session with a custom server.

const expressSession = require('next-session').expressSession
const promisifyStore = require('next-session').promisifyStore
const session = require('next-session').session
MemcachedStore = require("connect-memcached")(expressSession);

const server = express()
server.use(session({
        store: promisifyStore(new MemcachedStore({
            hosts: ["127.0.0.1:11211"],
            secret: "super-mega-secret"
        }))
    }))

This doesn't even return a Set-Cookie header. I've tried several methods but still no luck.

**Comment by hoangvvo** [comment]
If it's a custom server, I recommend just using `express-session`. It is more battle tested than this library. There is a bug with `next-session` that I'm aware of that sometimes makes it fail to set the cookie.

**Comment by hoangvvo** [comment]
> If it's a custom server, I recommend just using `express-session`. It is more battle tested than this library. There is a bug with `next-session` that I'm aware of that sometimes makes it fail to set the cookie.

This bug had already been fixed for awhile. It is fine to to `next-session` in customer server. I would recommend using `express-session` + `next-connect` **without** a custom server as seen [here](https://github.com/hoangvvo/nextjs-mongodb-app)

**Comment by hoangvvo** [comment]
`next-session` was only made because there was no way to use `express-session` and other middleware in Next.js without a custom server. However, now that `next-connect` was made to allow the use of middleware in Next.js, I would recommend to stick with `express-session` by using `next-connect`.
