### ISSUE TITLE
Improve View count example

### ISSUE THREAD

**Issue by dorinesinenco** [hoangvvo/next-session#26]
Hi, i have this setup
"dependencies": {
    "@formatjs/intl-relativetimeformat": "^2.8.3",
    "@formatjs/intl-utils": "^0.7.0",
    "@material-ui/core": "^4.3.3",
    "@material-ui/icons": "^4.2.1",
    "express": "^4.17.1",
    "formatjs": "^0.1.1",
    "intl": "^1.2.5",
    "isomorphic-unfetch": "^3.0.0",
    "js-cookie": "^2.2.1",
    "material-ui": "^0.20.2",
    "micro": "^9.3.4",
    "next": "9.0.5",
    "next-cookies": "^1.1.3",
    "next-i18n-routes": "^1.0.2",
    "next-i18next": "^1.1.2",
    "next-session": "^2.0.0",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-intl": "^3.1.13",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "redux-devtools-extension": "^2.13.8"
  }

and here is my /api/x.js test page
------------------------------------------------
import { withSession } from 'next-session';

const yourOptions = {}

const handler = (req, res) => {
    req.session.views = req.session.views ? (req.session.views + 1) : 0;
    res.send(`In this session, you have visited this website ${req.session.views} time(s).`)
};
export default withSession(handler, { ...yourOptions });

all i get is "0" after each page refresh

**Comment by dorinesinenco** [comment]
Nevermind i found the error, you didn't write the correct example in JS
this line will always set ZERO
req.session.views = req.session.views ? (req.session.views + 1) : 0;
i've modified it like so
req.session.views = req.session.views ? (req.session.views + 1) : 1; // which is in my opinion even closer to the real world :D

**Comment by hoangvvo** [comment]
Oh, that's my bad. Thanks for pointing it out. I will update the documentation accordingly.

**Comment by dorinesinenco** [comment]
:)
