### ISSUE TITLE
TypeError with connect-pg-simple Session Store

### ISSUE THREAD

**Issue by dbachrach** [hoangvvo/next-session#28]
We are using a postgres based express-compatible session store: https://github.com/voxpelli/node-connect-pg-simple. We get the following error though:

```
TypeError: Class constructor Store cannot be invoked without 'new'
```

This looks like the way next-session declares its Store does not conform to how express-session declares its Store.

You can compare

- https://github.com/expressjs/session/blob/master/session/store.js
- https://github.com/hoangvvo/next-session/blob/master/src/session/store.js

Unfortunately, next-session's usage of `class` makes it incompatible with some express-session compatible stores.

**Comment by hoangvvo** [comment]
Hey @dbachrach, sorry one more time. I did not consider this case, but this should be an easy fix. I will take care of it in the next few hours.

**Comment by revolunet** [comment]
By any chance, do you have any example of some PG persistent store ?

i cannot make `node-connect-pg-simple` work

**Comment by revolunet** [comment]
Look like `next-session` is waiting for a Promise for `Store.get` while `connect-pg-simple` use callbacks : https://github.com/voxpelli/node-connect-pg-simple/blob/master/index.js#L284

**Comment by hoangvvo** [comment]
@revolunet You need to use `promisifyStore` as shown in the [README](https://github.com/hoangvvo/next-session#compatibility-with-expressconnect-stores)
