### ISSUE TITLE
cookie.maxAge doesnt work

### ISSUE THREAD

**Issue by hgbe33** [hoangvvo/next-session#280]
I have set `cookie.maxAge` to 30 days (2592000s) and it used to work (@3.2.3). But it stopped working recently after updating to the latest version (@3.3.1). I was looking at [this line](https://github.com/hoangvvo/next-session/blob/cc9905c1b09a96d8120ed2a6386474d4d684c860/src/core.ts#L46) of the code and was wondering if this should be `req.session.cookie.expires` instead? Thanks.

**Comment by hoangvvo** [comment]
Hey, sorry for the trouble. It is correct, thank you! Fixed in `3.3.2`.
