### ISSUE TITLE
Multiple calls to res.end()

### ISSUE THREAD

**Issue by dbachrach** [hoangvvo/next-session#29]
We are running into an issue with how next-session intercepts res.end. If we do redirects, we will have multiple calls to res.end(). This looks to be fine and should just silently do nothing on the second occurence of res.end().

You can see that express-session handles this case: https://github.com/expressjs/session/blob/85682a2a56c5bdbed8d7e7cd2cc5e1343c951af6/index.js#L249

Which came in this commit:
https://github.com/expressjs/session/commit/7077190a76cf4bb3fcec3c2a040094901994785f

I think we should have similar logic in next-session like, so it handles multiple invocations of res.end():

```js
let ended = false;
//  Proxy res.end
res.end = function resEndProxy(...args) {
  if (ended) {
    return false;
  }

  ended = true;
  // ...
```

**Comment by hoangvvo** [comment]
Hey @dbachrach, sorry for the late reply and thanks for reporting.

Knowing the solution, feel free to make a PR yourself. Otherwise, I will take care of it ASAP.
