### ISSUE TITLE
Invalid expiry when maxAge is set and touchAfter is disabled

### ISSUE THREAD

**Issue by tlo-johnson** [hoangvvo/next-session#318]
Setting `cookie.maxAge` and disabling `touchAfter` results in incorrect session expiry date. 

Looks like it boils down to [this line of code](https://github.com/hoangvvo/next-session/blob/cc0410408fffa7d2967408d0516e41388620f85e/src/core.ts#L202) where maxAge should be added to the expiry.

**Comment by hoangvvo** [comment]
Thanks for pointing out, this is definitely a bug (a big one) and will be fixed in #283.

**Comment by hoangvvo** [comment]
Fix released in `3.4.0`

**Comment by tlo-johnson** [comment]
brilliant!! thx
