### ISSUE TITLE
Bugs! Sessions read from all browsers

### ISSUE THREAD

**Issue by aljabary** [hoangvvo/next-session#321]
Hi guys, i try use session, but I found my session data can read from all browser, I use 2 browser in same time (firefox and chrome) and in my page, resut is give same value from same session.

this my scripts:
```

var data=0;
export default class Home extends Component {
constructor (props) {
    super(props)
   data++; //incrementing
 }
 render() {
  let { path, url } = this.props;
  return ( <h1>{props}</h1>)
}
}

export async function getServerSideProps({ req, res }) {
  await applySession(req, res, {});
  req.session.views=data; //req.session.destroy();
  return {
    props: {
      views: req.session.views
    }
  }
}
```
Result:
### 3
in firefox show ### 3 too. in firefox should show 1 case I open firefox for one time

**Comment by hoangvvo** [comment]
I think it is because of the way you are using that data variable (and its scope). Doing so will make every server call in getServerSideProps to refer to that same variable (data). So it will be the same wherever you use it (firefox/chrome)
