### ISSUE TITLE
Documentation discussion: invoking connect function as middleware leads to event listener accumulation

### ISSUE THREAD

**Issue by georgekamar** [hoangvvo/next-session#327]
I didnt find anywhere to open a discussion so Im mentioning this here. 

In the documentation for this project I found that the connect function is called as a middleware like so: 

```
import { session } from 'next-session';

const handler = nextConnect()
  .use(session({ ...options }))
```

I found that when calling it that way, instead of saving what the function returns and using that, .on('connect') and .on('disconnect') event listeners start piling up every time the middleware function is called, leading to a maxListenersExceeded warning. This doesn't:

```
import { session } from 'next-session';

const mySession = session({ ...options });

const handler = nextConnect()
  .use(mySession)
```

Not sure if this is fine, Im interested in your feedback on this. If Im making a good point maybe it would be a good idea to update the ReadMe to avoid having to dig in the code to find out where the event listeners get added. 

Thanks

**Comment by hoangvvo** [comment]
This is definitely a really bad issue and should have been noted! Thanks for pointing it out.

Would you like to open a PR to update the README?

**Comment by georgekamar** [comment]
Yes dude Id love to. Please do correct my technical usage of the terms when I do as Im not sure of how rigorous I will be
