### ISSUE TITLE
ESM support

### ISSUE THREAD

**Issue by talentlessguy** [hoangvvo/next-session#333]
Would be great to have ESM support on next-session so it supports named imports:

```js
import { MemoryStore, session } from 'next-session'
```

the ESM support guide is here: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

probably because it's a more Next.js-centered project the better way would be to produce both CJS and ESM outputs.

**Comment by hoangvvo** [comment]
Just a note here: next-session v4 is ESM compatible.
