### ISSUE TITLE
Just not working :)

### ISSUE THREAD

**Issue by 1aerostorm** [hoangvvo/next-session#358]
Library is not working with actual Next version.

If you setting session in API handler, it will set. And it can be obtained in API handler. But if you will try to work with session in `getServerSideProps()`, there will be a conflict, and session will reset (rewrite). "Common" session in API handlers and in pages is not common actually.

How to reproduce:

1. Run following command:

```
yarn create next-app
```
with all defaults.

Result in `package.json` is:
```js
...
"next": "12.0.7",
...
```

2.

```
yarn add next-connect next-session
```
Result in `package.json` is:
```js
...
"next-connect": "^0.11.0",
"next-session": "^4.0.4",
...
```

3. lib/get-session.js

```js
import nextSession from "next-session";
export const getSession = nextSession();

```

4. Replace pages/api/hello.js code with following one:

```js
import { getSession } from "../../lib/get-session.js";

export default async function handler(req, res) {
  const session = await getSession(req, res);
  session.views = session.views ? session.views + 1 : 1;
  // Also available under req.session:
  // req.session.views = req.session.views ? req.session.views + 1 : 1;
  res.send(
    `In this session, you have visited this website ${session.views} time(s).`
  );
}
```

5. In pages/index.js add:
```js
import { getSession } from "../lib/get-session.js";
```

6. And also in pages/index.js, at bottom, add:
```js
export async function getServerSideProps({ req, res }) {
  const session = await getSession(req, res);
  session.views = session.views ? session.views + 1 : 1;
  // Also available under req.session:
  // req.session.views = req.session.views ? req.session.views + 1 : 1;
  console.log('VIEWS-SSP', session.views);
  return {
    props: {
      views: session.views,
    },
  };
}
```

7. Run it!

```
yarn run dev
```

8. Visit in browser 3 times: http://localhost:3000/api/hello
Output is "In this session, you have visited this website 3 time(s)."

9. Now visit http://localhost:3000.

Expected server log:
```
VIEWS-SSP 4
```

Actual server log:
```
VIEWS-SSP 1
warn  - You should not access 'res' after getServerSideProps resolves.
Read more: https://nextjs.org/docs/messages/gssp-no-mutating-res
warn  - You should not access 'res' after getServerSideProps resolves.
Read more: https://nextjs.org/docs/messages/gssp-no-mutating-res
warn  - You should not access 'res' after getServerSideProps resolves.
Read more: https://nextjs.org/docs/messages/gssp-no-mutating-res
warn  - You should not access 'res' after getServerSideProps resolves.
Read more: https://nextjs.org/docs/messages/gssp-no-mutating-res
warn  - You should not access 'res' after getServerSideProps resolves.
Read more: https://nextjs.org/docs/messages/gssp-no-mutating-res
warn  - You should not access 'res' after getServerSideProps resolves.
Read more: https://nextjs.org/docs/messages/gssp-no-mutating-res
warn  - You should not access 'res' after getServerSideProps resolves.
Read more: https://nextjs.org/docs/messages/gssp-no-mutating-res
```

9.1. Also, now visit http://localhost:3000/api/hello again.

Expected result: "In this session, you have visited this website 5 time(s)."

Actual result: "In this session, you have visited this website 1 time(s)."

So session just resets when we access it from `getServerSideProps()`.

---

Also tried `autoCommit: false`. Now there are no couples of warns when I access page, but session still resetting.

**Comment by hoangvvo** [comment]
Did you try it with an actual session store (backed by Redis, MongoDB). I do not understand Next.js architecture properly but perhaps there are different instances that are spinned up, causing two different `MemoryStore` instance. In that case, the only fix is to use a store that is backed by Redis, MongoDB, etc.

**Comment by 1aerostorm** [comment]
@hoangvvo 

> Did you try it with an actual session store (backed by Redis, MongoDB)?

No. I need `MemoryStore`. So I used `iron-session` instead.

**Comment by david-benes** [comment]
Had similar experience with the MemoryStore yesterday. Session was randomly lost due to lost cookie on the server.
I didn't have much time to experiment. Just letting know.

I switched to cookies-next as I needed only a peristent visitor id instead session functionality.

**Comment by hoangvvo** [comment]
Unfortunately, `MemoryStore` is meant to be used for testing and not for production used as stated in the README

> Warning The default session store (if options?.store is undefined), MemoryStore, DOES NOT work in production or serverless environment. You must use a [Session Store](https://github.com/hoangvvo/next-session#session-store).

This is the same case with `express-session`. If you are looking for something to have sessions without using a store `iron-session` is a better solution.

**Comment by spmsupun** [comment]
@david-benes thanks, I was trying this, and iron-session either they are working.
