### ISSUE TITLE
Session doesn't save

### ISSUE THREAD

**Issue by SemperFortis** [hoangvvo/next-session#72]
The session does not save anything even though autoCommit is passed into the options. `export default withSession(handler, { autoCommit: true, cookie: { maxAge: 2.628e9 } });` When I refresh and try to update the session before that, all the properties are gone. Is there a way to get that session by it's id? The docs aren't very clear about that.

**Comment by hoangvvo** [comment]
This sounds like a bug. `autoCommit` should be `true` by default.

Are you using serverless mode?

Did you restart the server? The default MemoryStore will be cleared if the server is restarted.

**Comment by SemperFortis** [comment]
Currently not severless, and the sever did not restart either. When I refresh the page all the session properties are gone, but when I log `Object.keys(req.sessionStore.sessions)` everything is there with a new key I believe? There is just no detailed documentation on how to access a specific one.

**Comment by hoangvvo** [comment]
@SemperFortis Can you provide a minimal reproduction. In the meantime, can you try downgrading to a lower version to see if it works?

**Comment by SemperFortis** [comment]
I believe I worded my issue wrong, I meant to ask is there docs on accessing MemoryStore?

**Comment by hoangvvo** [comment]
It is not in the doc, but you can do `await req.sessionStore.get(sid)` to get a session by an id

**Comment by SemperFortis** [comment]
And the sid is the cookie value or req.sessionId?

**Comment by hoangvvo** [comment]
Hey @SemperFortis, so did the session persists or it is gone after you refresh the page?

**Comment by SemperFortis** [comment]
Yes, the session persists. Thank you.
